#服务器
server:
    #端口号
    port: 9090
#日志配置
logging:
    #日志输出文件
    file: "./logs/server.log"
    #级别
    level:
        lifecycle: DEBUG

#数据库配置
spring:
    profiles:
        active: product-windows
    datasource:
        url: jdbc:oracle:thin:@192.168.1.7:1521:orcl
        username: webapp
        password: tgbyhn624
        driver-class-name: oracle.jdbc.OracleDriver

#项目中各个服务的配置
services:
    message-center:
        name: message-service
    #订货会用户信息查询
    auth:
        url: http://192.168.100.18:1866/servlets/binserv/Fair