server:
    port: 80
logging:
    file: "./logs/server.log"
    level:
        hello: DEBUG

spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.1.3:1521:orcl
        username: semirfair_18s1s2
        password: tgbyhn624